# Generated by Django 4.2.6 on 2023-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="files/")),
                ("file_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Temp_File_Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("existingPath", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("eof", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
