# Generated by Django 4.2.6 on 2023-10-30 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0003_alter_temp_file_path_existingpath"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=20)),
                ("head_count", models.IntegerField()),
                ("live_start", models.DateTimeField(default=django.utils.timezone.now)),
                ("local_video", models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("user_password", models.CharField(max_length=20)),
                ("user_validate", models.BooleanField(default=False)),
            ],
        ),
    ]
