# Generated by Django 4.2.6 on 2023-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0004_liveroom_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_favorite",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="user_img",
            field=models.ImageField(null=True, upload_to="_media/user_info"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_nickname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_validate",
            field=models.BooleanField(default=True),
        ),
    ]
