# Generated by Django 4.2.6 on 2023-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0006_alter_user_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_nickname",
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
