# Generated by Django 4.2.6 on 2023-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0008_remove_user_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_nickname",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
