# Generated by Django 4.2.6 on 2023-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0011_alter_user_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_img",
            field=models.FileField(null=True, upload_to="_media/user_info"),
        ),
    ]
