# Generated by Django 4.2.5 on 2023-10-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0012_alter_user_user_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("user_nickname", models.CharField(max_length=20, unique=True)),
                ("vote", models.IntegerField(default=0)),
                ("visited", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("content", models.CharField(max_length=200)),
                ("post_img", models.FileField(null=True, upload_to="post/")),
                ("category", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=20)),
                ("product_name", models.CharField(max_length=20)),
                ("sold_out", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="LiveRoom",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_img",
            field=models.FileField(null=True, upload_to="user_info/"),
        ),
    ]
