# Generated by Django 4.2.6 on 2023-10-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp1", "0014_alter_post_user_id_alter_post_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_img",
            field=models.FileField(default="post/default_file.jpg", upload_to="post/"),
        ),
    ]
